<header class="flex-shrink-0">
    <nav class='navbar navbar-expand-md navbar-dark bg-primary px-3'>

        <a class="navbar-brand" href="<?= $router->urlFor('index')?>"> <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                fill="white" class="bi bi-search-heart" viewBox="0 0 20 20">
                <path d="M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z" />
                <path
                    d="M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z" />
            </svg> Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link <?= $currentPage  === 'index' ? 'active' : '' ?>" href="<?= $router->urlFor('index')?>">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link <?= $currentPage === 'urls' ? 'active' : '' ?>" href="<?= $router->urlFor('urls.index')?>">Сайты</a>
                </li>

            </ul>
        </div>
    </nav>
</header>
