<div class="container-lg mt-3">
    <h1>Сайты</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($urls)): ?>

                    <?php foreach ($urls as $url): ?>
                        <?php
                        $id = htmlspecialchars($url['id']);
                        $name = htmlspecialchars($url['name']);
                        $createdAt = htmlspecialchars($url['created_at'] ?? '');
                        $statusCode = htmlspecialchars($url['status_code'] ?? '');
                        ?>
                        <tr>
                            <td><?= $id ?></td>
                            <td><a href="<?= $router->urlFor('urls.show', ['id' => $id]) ?>"> <?= $name ?></a></td>
                            <td><?= $createdAt ?></td>
                            <td><?= $statusCode ?></td>
                        </tr>
                    <?php endforeach ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
