<?php require_once __DIR__ . '/../header.html'; ?>

<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/">Главная</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/urls">Сайты</a>
        </li>

    </ul>
</div>
</nav>
</header>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $type => $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?= $type ?>" role="alert">
                <?= $message ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($url->getUrlName()); ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($url->getId()); ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url->getUrlName()); ?>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($url->getCreatedAt()); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($id); ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <br>

        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($checks)) : ?>
                    <?php foreach ($checks as $check): ?>
                        <tr>
                            <td><?= htmlspecialchars($check->getId()); ?></td>
                            <td><?= htmlspecialchars($check->getStatusCode()) ?? ''; ?></td>
                            <td><?= htmlspecialchars($check->getH1()) ?? ''; ?></td>
                            <td><?= htmlspecialchars($check->getTitle()) ?? ''; ?></td>
                            <td><?= htmlspecialchars($check->getDescription()) ?? ''; ?></td>
                            <td><?= htmlspecialchars($check->getCreatedAt()); ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</main>


<?php require_once __DIR__ . '/../footer.html'; ?>