<?php include __DIR__ . '/../header.html'; ?>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-success" role="alert">
                <?= $message ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($url->getUrlName()); ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($url->getId()); ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url->getUrlName()); ?>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($url->getCreatedAt()); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($id); ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($checks)) : ?>
                    <tr><?php foreach ($checks as $check): ?>
                            <th><?= isset($check->getId) ? htmlspecialchars($check->getId) : ''; ?></th>
                            <th><?= isset($check->getStatusCode) ? htmlspecialchars($check->getStatusCode) : ''; ?></th>
                            <th><?= isset($check->getH1) ? htmlspecialchars($check->getH1) : ''; ?></th>
                            <th><?= isset($check->getTitle) ? htmlspecialchars($check->getTitle) : ''; ?></th>
                            <th><?= isset($check->getDescription) ? htmlspecialchars($check->getDescription) : ''; ?></th>
                            <th><?= isset($check->getCreatedAt) ? htmlspecialchars($check->getCreatedAt) : ''; ?></th>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</main>


<?php include __DIR__ . '/../footer.html'; ?>