<?php require 'header.html'; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: ПРИКРУТИТЬ $urlName</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td>ПРИКРУТИТЬ $id</td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td>Прикрутить активная ссылка на $urlName</td>
                    </tr>
                    <tr>
                    <td>Дата создания</td>
                    <td>Прикрутить $createdAt</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/1/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody>
                     <?php //здесь должны быть проверки форичем ?>
                </tbody>
            </table>
    </div>
</main>


<?php require '../footer.html'; ?>