<?php include __DIR__ . '/../header.html'; ?>

<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/">Главная</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="/urls">Сайты</a>
        </li>

    </ul>
</div>
</nav>
</header>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $type => $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?= $type ?>" role="alert">
                <?= $message ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (isset($rows)): ?>
                        <?php foreach ($rows as $row): ?>
                            <tr>
                                <td><?= htmlspecialchars($row['id']); ?></td>
                                <td><a href="/urls/<?= htmlspecialchars($row['id']); ?>"> <?= htmlspecialchars($row['name']); ?> </a> </td>
                                <td><?= htmlspecialchars($row['created_at'] ?? ''); ?></td>
                                <td><?= htmlspecialchars($row['status_code'] ?? ''); ?></td>

                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php include __DIR__ . '/../footer.html'; ?>