<?php include __DIR__ . '/../header.html'; ?>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-success" role="alert">
                <?= $message ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>

<!-- сюда через foreach должны подтягиваться данные из БД checks (или из двух бд??) и название каждой страницы должно быть ссылкой на {id} if isset $check-->
                       
                        <td></td> 
                        <td></td>
                        <td></td>
                        <td></td> 
                        
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php include __DIR__ . '/../footer.html'; ?>