<?php require 'header.html'; ?>
<div class="alert alert-success" role="alert">
    flash сообщение
  </div>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>

<!-- сюда через foreach должны подтягиваться данные из БД и название каждой страницы должно быть ссылкой на {id} -->
                        <td></td> 
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php require 'footer.html'; ?>