<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
        crossorigin="anonymous"></script>
</head>

<body class="min-vh-100 d-flex flex-column">

    <?= $this->fetch('partials/header.phtml', [
        'currentPage' => $currentPage
    ]); ?>

    <!-- flash-сообщения, если они есть -->
    <?php if (isset($flash) ?? count($flash) > 0) : ?>
        <?php foreach ($flash as $type => $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-<?= $type ?>" role="alert">
                    <?= $message ?>
                </div>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>


    <main class="flex-grow-1">
        <?= $content ?>
    </main>

    <?= $this->fetch('partials/footer.phtml'); ?>


</body>

</html>
